name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on version tags, e.g., v1.0.0
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  
        run: twine upload dist/*
